### ISSUE TITLE
issue when downloading

### ISSUE THREAD

**Issue by ggaggio19** [RadekSimkanic/Linux-SDM-Downloader#1]
I always obtain this error:

<edv>1352999256^^MPjVAqIFQNR30euxOTVMMyzx4Naqhjeua8DrbQ9Dzap6RMcB4hv3TEPyDbSsmWpC54837271</edv>
 Created 
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 34, in main
    d.execute()
  File "main.py", line 76, in execute
    if self.downloadFiles() == False:
  File "main.py", line 222, in downloadFiles
    listUrl = downloadUrl.split('.')
AttributeError: 'NoneType' object has no attribute 'split'

I've bs4 and I've already modified from BeautifulSoup in from bs4 in main.py

**Comment by RadekSimkanic** [comment]
Can you send me SDX file and your modified main.py to gulliver.www@seznam.cz ? So that I find problem and fixed it.

**Comment by ggaggio19** [comment]
Of course, I'm sending you it tomorrows when I'm home.

**Comment by RadekSimkanic** [comment]
Thank you, I found problem and fixed it. Now you update to actual source code and eventually uncomment line #19 ( `from bs4 import BeautifulSoup as Soup`) and comment line #17 ( `from BeautifulSoup import BeautifulSoup as Soup`). Now is script ready also to bs4 ;).

**Comment by ggaggio19** [comment]
Thank you very much. I'll try it tomorrow.

Best regards.

Il giorno dom 8 feb 2015 19:19 Radek Simkanič notifications@github.com ha
scritto:
