### ISSUE TITLE
Dont work on ubuntu 16.04

### ISSUE THREAD

**Issue by Squiercg** [RadekSimkanic/Linux-SDM-Downloader#11]
I get the following error trying to use on ubuntu.

```
augusto@augusto-dell:~/git/Linux-SDM-Downloader$ python main.py /home/augusto/Downloads/100453364449.sdx
Info: Opening SDX file
Info: Parsing URL
Info: Downloading main page
Info: Parsing done!
Info: Parsing done!
Choose file:
    Windows 10 (Multiple Editions)
    #1 | pt_windows_10_multiple_editions_version_1511_updated_apr_2016_x64_dvd_8725202.iso
    #2 | pt_windows_10_multiple_editions_version_1511_updated_apr_2016_x86_dvd_8712726.iso
    #3 | pt_windows_server_2012_r2_with_update_x64_dvd_4048515.01.sdc
    Windows Server 2012 R2
    #4 | pt_windows_10_multiple_editions_version_1511_updated_apr_2016_x86_dvd_8712726.iso
    #5 | pt_windows_server_2012_r2_with_update_x64_dvd_4048515.01.sdc
Please select file via number 1 - 3: 1
Info: Creating URL
Info: Downloading page contains download link
Info: Parsing page
Info: Creating .key file
Traceback (most recent call last):
  File "main.py", line 403, in <module>
    main()
  File "main.py", line 34, in main
    d.execute()
  File "main.py", line 77, in execute
    if self._downloadFiles() == False:
  File "main.py", line 202, in _downloadFiles
    f.write(edv)
TypeError: expected a string or other character buffer object
augusto@augusto-dell:~/git/Linux-SDM-Downloader$
```

**Comment by RadekSimkanic** [comment]
could you send me your .sdx file for simulate this situation to be able to modify or repair script.
My email is gulliver_www(A T)seznam_cz (underscores replace for dots)

**Comment by Squiercg** [comment]
2016-06-30 6:48 GMT-04:00 Radek Simkanič <notifications@github.com>:

> could you send me your .sdx file for simulate this situation to be able to
> modify or repair script.
> My email is gulliver_www(A T)seznam_cz (underscores replace for dots)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/RadekSimkanic/Linux-SDM-Downloader/issues/11#issuecomment-229625170>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB8JOE6Q4Ca9SJXt-KvLDRQJHUFYTIprks5qQ57tgaJpZM4JAe6j>
> .
>



-- 
Grato
Augusto C. A. Ribas

Site Pessoal: http://recologia.com.br/ <http://augustoribas.heliohost.org>
Github: https://github.com/Squiercg
Lattes: http://lattes.cnpq.br/7355685961127056

**Comment by Squiercg** [comment]
What is your e-mail?

**Comment by RadekSimkanic** [comment]
Please try again and tell me, whether is it now ok
