### ISSUE TITLE
Problems downloading iso (rather than sdc)

### ISSUE THREAD

**Issue by ajgpitch** [RadekSimkanic/Linux-SDM-Downloader#2]
First of all thanks for your excellent program.
For some reason 2 out of the 6 things I ordered from DreamSpark are .iso rather than .sdc files
These files are Windows 10 64 bit by the way.
I am not sure why they are iso rather than sdc.
Anyway, this program failed to download them.

**Comment by RadekSimkanic** [comment]
Hi, 
could you send me your .sdx file for simulate this situation to be able to modify or repair script.
My email is gulliver_www(A T)seznam_cz (underscores replace for dots)

Radek

**Comment by RadekSimkanic** [comment]
Hi, 
thank you for your .sdx file. I found problem, I must rewrite script. When I fix it, so I put there information.

Radek

**Comment by ajgpitch** [comment]
Great,
thank you

**Comment by RadekSimkanic** [comment]
Hi, 

now is possible download ISO file, please try it.

Radek

**Comment by ajgpitch** [comment]
I gave it a try, but I get an error. Program output follows.
btw I also have to change BS import line to:
from bs4 import BeautifulSoup as Soup

 $ python main.py '/data/Install/100419954443.sdx' 
Info: Opening SDX file
Info: Parsing URL
Info: Downloading main page
Info: Parsing done!
Info: Parsing done!
Info: Parsing done!
Choose file:
    Windows 7 Professional
    #1 | en_windows_7_professional_with_sp1_x86_dvd_u_677056.01.sdc
    #2 | en_windows_7_professional_with_sp1_x64_dvd_u_676939.01.sdc
    Windows 10 N (Multiple Editions)
    #3 | en-gb_windows_10_n_multiple_editions_x86_dvd_6846905.iso
    #4 | en-gb_windows_10_n_multiple_editions_x64_dvd_6846897.iso
    Windows 8.1 Professional
    #5 | en-gb_windows_8.1_with_update_x86_dvd_4048086.01.sdc
    #6 | en-gb_windows_8.1_with_update_x64_dvd_4048142.01.sdc
Please select file via number 1 - 6: 4
Info: Creating URL
Traceback (most recent call last):
  File "main.py", line 401, in <module>
    main()
  File "main.py", line 36, in main
    d.execute()
  File "main.py", line 76, in execute
    if self._downloadFiles() == False:
  File "main.py", line 158, in _downloadFiles
    url = parser.getDownloadUrl(
AttributeError: 'NoneType' object has no attribute 'getDownloadUrl'

**Comment by RadekSimkanic** [comment]
oh, I look at it.

**Comment by RadekSimkanic** [comment]
Fixed. Is it ok? :-)

**Comment by ajgpitch** [comment]
Sorry for delay. Yes, I have found that I can download both SDC and ISO files now.
Thank you very much for this fix

**Comment by RadekSimkanic** [comment]
welcome
