### ISSUE TITLE
Info: The .key file is not necessary.

### ISSUE THREAD

**Issue by azhao12345** [RadekSimkanic/Linux-SDM-Downloader#8]
I'm not sure how to extract the file without the key file.

**Comment by RadekSimkanic** [comment]
What do you have downloaded and how you did? Pleas describe me your steps what you did.

**Comment by azhao12345** [comment]
Hi,

I used the program to try to download an sdx file, and it gave this message.
"The .key file is not necessary."

The download is for mathematica 10.3.  I can send you more information in pm if you need it.

**Comment by RadekSimkanic** [comment]
could you send me your .sdx file for simulate this situation to be able to modify or repair script.
My email is gulliver_www(A T)seznam_cz (underscores replace for dots)

**Comment by RadekSimkanic** [comment]
I tested download via your sdx file. Unfortunately I don't have access to Caltech network. Could you try download it via  Caltech VPN  connection.

**Comment by RadekSimkanic** [comment]
close
